### ISSUE TITLE
All Links in Table Of Contents are Dead.

### ISSUE THREAD

**Issue by Opeth001** [Unity-Technologies/EntityComponentSystemSamples#101]
The Title describes everything.

**Comment by jo3w4rd** [comment]
Thanks for the report. This problem has been fixed in the source file (which is in a private repository) and so will be fixed here the next time we push from that repo to this one. 

(For what it is worth, the TableOfContents.md file is required for our package documentation generator. Please use index.md or manual.md as the entry points to the documentation.)

**Comment by Opeth001** [comment]
Thanks for everything you do here!
Unity ECS is my new hobby, i come back here everyday to see if you published something new . ^_^
