### ISSUE TITLE
Entities version 0.0.24  PositionComponent and RotationComponent  do not add to the gameobject

### ISSUE THREAD

**Issue by Prog-Maker** [Unity-Technologies/EntityComponentSystemSamples#102]
Error
Cant` add script component "PositionComponent" because the script class cannot be found. Make sure ... bla bla bla

**Comment by StewMcc** [comment]
com.unity.entities@0.0.12-preview.24\Unity.Transforms.Hybrid\PositionProxy.cs

Proxies (ComponentWrapper) have been moved into the hybrid area, so need the change from old PositionComponent.cs which is now just pure ECS stuff, and PositionProxy.cs being the new wrappers for the hybrid ECS.

So any old prefabs/game objects with the old PositionComponent will throw errors as doesn't exist in that file anymore?

**Comment by Andre-Houston** [comment]
Hi, I have a similar issue, however I seem to be missing the proxy files entirely after the upgrade in the package manager? 
Error: "The type or namespace name 'PositionProxy' could not be found". 
Same for rotation, both errors stem from the com.unity.entities@0.0.12-preview.24\Unity.Transforms.Editor\TransformComponentEditors.cs

I tried to downgrade to preview.23 and then re-upgrade and still experienced the same issue

**Comment by Zeekar** [comment]
I'm experiencing the same issue as @Andre-Houston 
Is there a temporary work around while this is worked on?

**Comment by Andre-Houston** [comment]
After downgrading to preview.23 and back to 24 today the proxy files are present.

**Comment by Opeth001** [comment]
Guys it's not an issue they changed the position and rotation components names to PositionProxy and RotationProxy.

**Comment by davidv-unity** [comment]
Hi there, within dots we generally use the term `Translation` instead of `Position` now.
You can find examples of the new conversion workflow in the Samples, e.g. [here](https://github.com/Unity-Technologies/EntityComponentSystemSamples/blob/master/Samples/Assets/HelloECS/HelloCube_01_ForEach/RotationSpeedProxy.cs). Please note that the other approaches have been deprecated and will eventually be removed in future releases.
Kind regards!
