### ISSUE TITLE
Entity packages to 0.0.12 preview-24 errors

### ISSUE THREAD

**Issue by castana1962** [Unity-Technologies/EntityComponentSystemSamples#125]
Hi All
Since I am looking for some way to reduce the overhead when working with meshes with ECS, I am trying this repo in Github made with ECS and Entities package 0.0.12 preview 21 more info here

https://github.com/tertle/MeshDemo/blob/master/Assets/Scripts/Systems/Mesh/MeshSystem.cs

So, I opened this project with Unity 2018.3f2 since that was done with Unity version and it works fine but since that the developer told me that this project should be updated to the new ForEach Api, for it, I updated it to Entities package 0.0.12 preview 24-timestampfix and then I got the following errors
-Assembly has reference to non-existent assembly 'Unity.Rendering.Hybrid' (Assets/Scripts/MeshDemo.asmdef)

-'Unity.Entities.GameObjectEntity' is missing the class attribute 'ExtensionOfNativeClass'!

-Unity.Entities.GameObjectEntity' is missing the class attribute 'ExtensionOfNativeClass'!

For it,   Could anybody to help me to fix it, Would it be possible?
Thanks for your time
Best Regards
Alejandro

**Comment by davidv-unity** [comment]
Hi,
As this is an external repository you might want to file an issue there, however, this might help: 
There has been quite a few changes and optimizations going on and some of them required changes in native Unity, so for the current `ECS` and `Unity.Physics` samples you need to use `2019.1`.
I recommend you try to upgrade to project to a new unity version (`b05` is required for `preview.25` and later, current version is `0b8` which is also supported and might be required in the future).
Note that the package is still in `preview` which means that APIs can get changed or even be removed, we're working on stabilising them but the focus is on *getting it right*, so there might be a few pain points due to this (however when understanding the principles behind data oriented design they should be minimal). Please try if updating helps in your case, otherwise reach out to the forums for help as the issue system is meant to be for bugs directly related to ecs/physics, we're happy to help you out there!

**Comment by castana1962** [comment]
Hi
Thanks for your help and patience!!!
Regards
Alejandro

**Comment by davidv-unity** [comment]
Did upgrading (Unity and entities) work for you? If you feel like there is anything we could do about this (by changing code in this repo) or that this is indeed a bug on our side please reopen the issue. As for now we can not look into fixing external projects although we are happy to help in the forums wherever possible!

**Comment by castana1962** [comment]
Hi david
Please do not worry, You are a very kind guy.... Thanks a lot....
I understand you cannot answer about this External repo. I added a post in this repo and if I get any answer to fix it, I will tell you, since I guess that maybe it could help to Unity for the mesh package in the future !!!
Hope this help !!!
PS. I tried this Mesh project in Unity 2019.1 b8 and Entities 0.0.12 preview 29 and I got multiple errors...
Regards
Alejandro
