### ISSUE TITLE
PlayerInput IComponentData contains logic

### ISSUE THREAD

**Issue by sschmid** [Unity-Technologies/EntityComponentSystemSamples#14]
[PlayerInput](https://github.com/Unity-Technologies/EntityComponentSystemSamples/blob/master/TwoStickShooter/Pure/Assets/GameCode/ComponentTypes.cs#L14) contains logic.

IComponentData should only contain data. Taken from your docs
> ... the name refers directly to the fact that [IComponentData] only stores data

A computed getter like `bool Fire` is logic and also not serializable. Shouldn't this code be in a system?

**Comment by NVentimiglia** [comment]
Perhaps there is an unwritten exception for non-mutating computational only logic?

**Comment by gabstv** [comment]
Maybe the ```Fire``` function is compiled inline inside the job that is using it (since it is read only and contained). But nevertheless it should be documented.

**Comment by davidv-unity** [comment]
Hi, as this is still an _open_ issue: This remark is "correct". All data should be `public` as data transparency is an important aspect of dots. There is nothing preventing you from having a property to compute something based on that data, it is just not recommended. It is hard to answer such question for all scenarios, but the current recommendation is to have them as external functions `()` so that it is obvious that they are not part of the data that is stored (e.g. the `length` of any `floatn` vector type). Whenever there are questions about this feel free to reopen and post them or visit the forums.
