### ISSUE TITLE
Cannot use Position2D or Heading2D

### ISSUE THREAD

**Issue by viswadeep-sarangi** [Unity-Technologies/EntityComponentSystemSamples#178]
I'm currently following a slightly older tutorial to understand the ECS system. The tutorial suggests using the Position2D and the Heading2D types when creating an Archetype. 
But I haven't been able to find how to include the packages that contain the definitions of Position2D or Heading2D yet. 
Has there been an update that has removed these? 
Hope I'm not missing something important.

**Comment by Drealmer** [comment]
We never had those components as part of the core entities package. The likely explanation is that those are either part of the tutorial you're looking at, or from another package that it imports.
If that doesn't help, please ask in our DOTS forum https://forum.unity.com/forums/data-oriented-technology-stack.147/
And also please link to the tutorial you're using for context.
I'm closing this now, since it's not really an issue related to this repository.
