### ISSUE TITLE
Why does PlayerData have a Length ?

### ISSUE THREAD

**Issue by NVentimiglia** [Unity-Technologies/EntityComponentSystemSamples#23]
Why does PlayerData have a Length? Why not check PlayerData.Input.Length? How is this hydrated?

// SEE THIS LINE

```
public class PlayerInputSystem : ComponentSystem
    {
        struct PlayerData
        {            
            // SEE THIS LINE
            public int Length;

            public ComponentDataArray<PlayerInput> Input;
        }

        [Inject] private PlayerData m_Players;

        protected override void OnUpdate()
        {
            float dt = Time.deltaTime;
            
            // SEE THIS LINE
            for (int i = 0; i < m_Players.Length; ++i)
            {
                UpdatePlayerInput(i, dt);
            }
        }

        private void UpdatePlayerInput(int i, float dt)
        {
            PlayerInput pi;

            pi.Move.x = Input.GetAxis("Horizontal");
            pi.Move.y = Input.GetAxis("Vertical");
            pi.Shoot.x = Input.GetAxis("ShootX");
            pi.Shoot.y = Input.GetAxis("ShootY");

            // SEE THIS LINE
            pi.FireCooldown = Mathf.Max(0.0f, m_Players.Input[i].FireCooldown - dt);

            // SEE THIS LINE
            m_Players.Input[i] = pi;
        }
    }
```

**Comment by darbotron** [comment]
I'm 99% sure this is because the [Inject] attribute expects whatever struct it's injecting to be a struct of arrays (SoA) where all the contained ComponentDataArray<T> have the same length. 

The generalised usage of the [Inject] idiom (e.g. see the struct used by other classes derived from ComponentSystem) makes more obvious sense since the injected structs typically have multiple ComponentDataArray with different component types.

**Comment by NVentimiglia** [comment]
Not sure I like the competing values. Will confuse others. 

Maybe an interface defining why we need this? Will exclusion break things?

**Comment by starikcetin** [comment]
@NVentimiglia 
What do you mean by competing values?

**Comment by starikcetin** [comment]
@NVentimiglia 
I still don't understand why you think they are _competing_.

When you are injecting multiple arrays in the same struct, they are all injected in parallel in terms of entities. Therefore they all have the same length. Instead of checking the length of every single array (which would be the same for all of them), I very much prefer injecting a single length variable.

**Comment by NVentimiglia** [comment]
@starikcetin 

Maybe I am confused. So it is possible for these values to be different if we have multiple arrays? Are the rules defining what this 'Length' value means documented somewhere?

**Comment by NVentimiglia** [comment]
Gotcha, so if Foos is 3 and Bars is 2, Length will be 3? Is that possible with how groups work? I was assuming that If I requested a group with Foo and Bar, I would get only entities with both (both 3).

**Comment by starikcetin** [comment]
@NVentimigla 

Your assumption is correct. You only get entities that has both of the components. Hence why the arrays are parallel, and that they have the same length.

**Comment by Prastiwar** [comment]
```cs
struct Group
{
    public int Length;
    public EntityArray Entities;
    public ComponentDataArray<Foo> Foos;
    public ComponentDataArray<Bar> Bars;
}
```
***Group*** is group of all Entities in active world that have Foo ***and*** Bar component
It's like array of entities with references to specific given components.
So - Group is like EntityArray but with references to components, EntityArray itself is just array of Entities (and entity is just an index in map)
***Length*** is length of EntityArray, so also Length of Foos and Bars, because each entity has Foo and Bar component

It's more obvious in this case 
```cs
for(int i; i < m_group.Length; i++) // iterate over all entities
{
    // It's safe to iterate like that, because every array in group has the same length
    var actualEntity = m_group.Entities[i];  // Actual iterating Entity
    var actualFoo    = m_group.Foos[i];      // Foo component "attached" to actualEntity
    var actualBar    = m_group.Bards[i];     // Bar component "attached" to actualEntity
}
``` 
Using m_group.Foos.Length or m_group.Bar.Length would be a bit confusing in this case.

Summary -  every array in injected group would have same Length, because it's length of Entities and each entity has every given component

**Comment by NVentimiglia** [comment]
@Prastiwar Super helpful
