### ISSUE TITLE
Multiple links broken in the documentation

### ISSUE THREAD

**Issue by JeromeJ** [Unity-Technologies/EntityComponentSystemSamples#38]
https://github.com/Unity-Technologies/EntityComponentSystemSamples/issues/19#issuecomment-383081300 On the 20 April it's been said it was a known issue and they plan to fix it.

Other issues referencing the same problem:

#27 , #35 , #19 

(This issue is an attempt to unify those and address it altogether)

**EDIT:** It seems that other repo wasn't ready, got deleted and hasn't been put back on yet.
https://forum.unity.com/threads/github-ecsjobdemos-404.517591/

I haven't found it on archive.org neither.

**Comment by HermitStudio** [comment]
Hi Jerome,

We have found two issues with the links and have fixed these now and they will become public in the next update/sync to this repo. 

The problem was that the preview code gets changed around sometimes, and so the filepath is no longer valid. These links were corrected. 

Then in another ticket we noticed that whenever a script was linked to under the _/Package_ folder it didn't work in the public repo because these scripts are not included when a sync is done. So they create 404, even though they work locally. So I've removed these links and just included text to the location of the file. So you can still find it within your own _/Package_ folder.

I'll close this ticket since all the issues have been resolved now.

I hope that helps and thanks for the feedback!

Regards,

Corrie
