### ISSUE TITLE
How you test system from ECS?

### ISSUE THREAD

**Issue by MadDaelim** [Unity-Technologies/EntityComponentSystemSamples#42]
**1. Question**
There is a easy way to test single system? 
I write UnityTest and run them with TestRunner but they look more like integration tests than unit tests and almost always is hard to assert result for them.

**2. Request**
Could you add unit tests to yours samples?
It would be grate if i could pass to system prepared entity, call update function and check changes on entity.

**3. Missing**
You have paragraph in your vision "Our code comes with full unit test coverage" but you missing "Our feature is easy unit testable".

**Comment by amechtley** [comment]
Hi! If you haven't found them already, the best idea is to look at the tests in the entities package (e.g., Unity.Transforms.Tests). Depending what you're looking for though, I'm not sure there's a way to create a "unit test" as such, since you cannot mock all the system's dependencies (e.g., component data it needs).
