### ISSUE TITLE
Dead Link 'Default World creation code' 404

### ISSUE THREAD

**Issue by PaulUsul** [Unity-Technologies/EntityComponentSystemSamples#61]
The link to 

Default World creation code
https://github.com/Unity-Technologies/EntityComponentSystemSamples/blob/master/ECSJobDemos/Packages/com.unity.entities/Unity.Entities.Hybrid/Injection/DefaultWorldInitialization.cs

and 
Automatic bootstrap entry point
https://github.com/Unity-Technologies/EntityComponentSystemSamples/blob/master/ECSJobDemos/Packages/com.unity.entities/Unity.Entities.Hybrid/Injection/AutomaticWorldBootstrap.cs

**Comment by KonH** [comment]
It looks like these links are related to internal package content for one of the examples (https://github.com/Unity-Technologies/UniteAustinTechnicalPresentation/blob/master/StressTesting/Packages/manifest.json).
I can download it manually and place to this repository, but not sure about correctness of this approach.

**Comment by PaulUsul** [comment]
For some reason I forgot to mention where this happens.

it's found from wiki->documentation->ECS features in detail
https://github.com/Unity-Technologies/EntityComponentSystemSamples/blob/master/Documentation/content/ecs_in_detail.md#world

**Comment by HermitStudio** [comment]
Hi Paul,

We found the issue with the World page (and a few others). It was due to the fact I was linking to a script that is available locally/in development but was not available in the public repo. Any script in the _/Package_ folder was affected. So I've removed all affected links and added text showing the file path so you can find it in your own _/Package_ folder.

I'll close the issue now.

Thanks for the feedback!

Regards,

Corrie
