### ISSUE TITLE
BurstCompile

### ISSUE THREAD

**Issue by myl2232** [Unity-Technologies/EntityComponentSystemSamples#70]
hi, when should i add BurstCompile attrubute?
like this:
        [BurstCompile]
        struct CalculatePositionsJob : IJobParallelFor
        {
         }

**Comment by Opeth001** [comment]
Hi ^_^
i dont think that the New Burst Compiler need the [BurstCompile] attrubute anymore.
but from what i found on google you just have to add [BurstCompile] like the exemple you provided and you can also add params like:

// Set CompileSynchronously to true to make sure that the method will not be compiled asynchronously
[BurstCompile(CompileSynchronously = true)] 

To make sure you get a better performance always use Unity.Mathematics variables and functions instead of math.AnyFunction.  eg change your Vector3 to float3 ...

**Comment by davidv-unity** [comment]
Hi, your usage is correct but to prevent any misunderstandings: it is still opt-in (until (after) burst leaves preview) so put `[BurstCompile]` above any job struct you want to be compiled with burst like you did.
