### ISSUE TITLE
HelloCubeRotationSpeed breaks down after changing speed value in editor

### ISSUE THREAD

**Issue by Hitomilras** [Unity-Technologies/EntityComponentSystemSamples#94]
I cloned this repository to my mac and try to test a little bit all the scenes.

In HelloCubeRotationSpeed i see some strange behaviour. If i try to change Value (in HelloRotationSpeedComponent) in editor (not in play mode) and after this start play mode, i see that cube rotates a little bit, then return to its start rotation, then rotates a little bit, then return again to its starting rotation and so on. 

IMPORTANT. It reproduces only if you actually select RotatingCube game object in hierarchy and there is inspector editor window opened and shows the components list of RotatingCube game object. If i select any other game object in scene it works fine.

May be it's normal and i just don't know something important about changing components data in editor, but i don't think that way.

Unity version 2018.3.1f1 (may be that's the reason)

**Comment by amechtley** [comment]
This is just a problem with how quaternion fields are drawn in the Inspector. It is fixed in the latest mathematics package, but unfortunately it did not land in time for us to bump the version in the entities manifest.

You should be able to fix this problem by either:
- Deselect the rotating object or collapse the Rotation component in the Inspector
- Manually update the mathematics package in your project to preview20

**Comment by Hitomilras** [comment]
Thank you
